---
# tasks file for utserver

- apt: update_cache=yes cache_valid_time=3600
  when: utserver_apt_update

- apt: name={{ item }} state=present
  with_items:
    - libssl0.9.8
    - libssl1.0.0

- get_url: url={{ utserver_download_url }} dest={{ utserver_download_dest }}
  when: "utserver_download_url.startswith(('http://', 'https://'))"

- copy: src={{ utserver_download_url }} dest={{ utserver_download_dest }}
  when: "not utserver_download_url.startswith(('http://', 'https://'))"

- unarchive: src={{ utserver_download_dest }} dest={{ utserver_install_dest }} creates={{ utserver_link_src }}

- file: src={{ utserver_link_src }} dest={{ utserver_link_dest }} state=link


# install custom webui if available
- get_url: url={{ utserver_webui_url }} dest={{ utserver_link_src }}/webui.custom.zip
  when: utserver_webui_url

- file: src={{ utserver_link_src }}/webui.custom.zip dest={{ utserver_link_src }}/webui.zip state=link force=yes
  when: utserver_webui_url